# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Take screenshots for playstore"
  lane :take_screenshots do
    gradle(
      task: 'assemble assembleAndroidTest'
    )

    apk_path = Dir.glob("../**/*-debug.apk").first
    test_apk_path = Dir.glob("../**/*-debug-androidTest.apk").first

    screengrab(
      clear_previous_screenshots: true,
      locales: ["en-AU"],
      app_package_name: 'nz.org.cacophony.birdmonitor',
      app_apk_path: File.absolute_path(apk_path),
      tests_apk_path:  File.absolute_path(test_apk_path),
      use_tests_in_classes:(['nz.org.cacophony.birdmonitor.ScreenshotGen']),
      test_instrumentation_runner: 'androidx.test.runner.AndroidJUnitRunner'
    )
  end

  desc "Submit a new Beta Build to Playstore"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store(track: 'beta')
  end

  desc "Update meta data on playstore"
  lane :update_meta do
    upload_to_play_store(
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      skip_upload_apk: true,
      skip_upload_aab: true,
    )
    end

  desc "Deploy without building release"
  lane :release do
    upload_to_play_store(
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      apk: "bird-monitor-signed.apk"
    )
    end
end